version: '3.8'

services:
  airflow:
    build: .
    container_name: airflow
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
    ports:
      - "8090:8080"
    volumes:
      - ./dbt-profile:/home/airflow/.dbt
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow-data:/opt/airflow
      - ../project-1-media-library-pipeline:/opt/airflow/project-1-media-library-pipeline
    command: >
      bash -c "airflow db init &&
      rm -f /opt/airflow/airflow-webserver.pid &&
      airflow webserver & airflow scheduler"
